### ISSUE TITLE
Implement button API logic

### ISSUE THREAD

**Issue by ultramolecular** [ultramolecular/cs378-p4#7]
We have three buttons and one search function to cover:

1. **Featured Events**: showcases popular events happening soon (ideally based on the user's location).
2. **Just Announced**: displays most recently announced events to capture the excitement of fresh listings.
3. **This Weekend**: filters events to show what is happening the upcoming weekend.
4. **Search by city**: allows users to search a city and find music events there.

**Comment by Sky-De** [comment]
@ultramolecular assign this to me please, thanks

**Comment by ultramolecular** [comment]
Implemented all 4 functions with 4ad6e3e, however, default data isn't automatically shown when a user loads in the page for the first time (or when they refresh). I will mark this as resolved when this is achieved.

**Comment by ultramolecular** [comment]
Implemented automatically displaying events once a user allows location permissions with 05dd9908af8370cb057be68c15b987f01fbed780; all buttons and functionality work.
